---
name: release-build

on: 
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: docker_buildx
        with:
          install: true

      - name: Setup cache
        uses: actions/cache@v2
        id: docker_cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: false
          context: ./
          file: ./Dockerfile
          outputs: type=local,dest=.
          builder: ${{ steps.docker_buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Make release
        uses: marvinpinto/action-automatic-releases@latest
        id: release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Resume 
          files: |
            resume.pdf
